<?php

define( 'PLUGINS_RELEASES_UPLOAD_THRESHOLD_LEVEL_DEFAULT', ADMINISTRATOR );
define( 'PLUGINS_RELEASES_DOWNLOAD_THRESHOLD_LEVEL_DEFAULT', UPDATER );
define( 'PLUGINS_RELEASES_VIEW_THRESHOLD_LEVEL_DEFAULT', UPDATER );
define( 'PLUGINS_RELEASES_UPLOAD_METHOD_DEFAULT', DISK );
define( 'PLUGINS_RELEASES_DISK_DIR_DEFAULT', '' );
define( 'PLUGINS_RELEASES_FTP_SERVER_DEFAULT', '' );
define( 'PLUGINS_RELEASES_FTP_USER_DEFAULT', '' );
define( 'PLUGINS_RELEASES_FTP_PASS_DEFAULT', '' );
define( 'PLUGINS_RELEASES_FILE_NUMBER_DEFAULT', 1 );
define( 'PLUGINS_RELEASES_NOTIFICATION_ENABLE_DEFAULT', OFF );
define( 'PLUGINS_RELEASES_NOTIFY_HANDLER_DEFAULT', ON );
define( 'PLUGINS_RELEASES_NOTIFY_REPORTER_DEFAULT', OFF );
define( 'PLUGINS_RELEASES_NOTIFY_EMAIL_DEFAULT', '' );
define( 'PLUGINS_RELEASES_EMAIL_SUBJECT_DEFAULT', '[*P]: *c new file(s) has(ve) been added.' );
define( 'PLUGINS_RELEASES_EMAIL_TEMPLATE_DEFAULT', 'default' );
define( 'PLUGINS_RELEASES_ERROR_FILE_NOT_FOUND', 510 );
